// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: rpc_server_etcd.proto

package rpc_server_etcd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcServerEtcd_Ping_FullMethodName = "/rpc_server_etcd.Rpc_server_etcd/Ping"
)

// RpcServerEtcdClient is the client API for RpcServerEtcd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcServerEtcdClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rpcServerEtcdClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcServerEtcdClient(cc grpc.ClientConnInterface) RpcServerEtcdClient {
	return &rpcServerEtcdClient{cc}
}

func (c *rpcServerEtcdClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RpcServerEtcd_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcServerEtcdServer is the server API for RpcServerEtcd service.
// All implementations must embed UnimplementedRpcServerEtcdServer
// for forward compatibility.
type RpcServerEtcdServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRpcServerEtcdServer()
}

// UnimplementedRpcServerEtcdServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcServerEtcdServer struct{}

func (UnimplementedRpcServerEtcdServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcServerEtcdServer) mustEmbedUnimplementedRpcServerEtcdServer() {}
func (UnimplementedRpcServerEtcdServer) testEmbeddedByValue()                       {}

// UnsafeRpcServerEtcdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcServerEtcdServer will
// result in compilation errors.
type UnsafeRpcServerEtcdServer interface {
	mustEmbedUnimplementedRpcServerEtcdServer()
}

func RegisterRpcServerEtcdServer(s grpc.ServiceRegistrar, srv RpcServerEtcdServer) {
	// If the following call pancis, it indicates UnimplementedRpcServerEtcdServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcServerEtcd_ServiceDesc, srv)
}

func _RpcServerEtcd_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServerEtcdServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcServerEtcd_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServerEtcdServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcServerEtcd_ServiceDesc is the grpc.ServiceDesc for RpcServerEtcd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcServerEtcd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_server_etcd.Rpc_server_etcd",
	HandlerType: (*RpcServerEtcdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RpcServerEtcd_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_server_etcd.proto",
}
