// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: api/helloworld.proto

package helloworld

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/restful"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// HelloworldService defines service.
type HelloworldService interface {
	// SayHello RESTful HTTP接口：通过用户ID获取问候信息
	//  会内部调用UserService获取用户信息
	// 映射 url: /v1/greeter/hello?user_id=1231
	SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error)
	// CreateUser RESTful HTTP接口：创建用户（内部调用UserService的扩展接口）
	CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error)
}

func HelloworldService_SayHello_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(HelloworldService).SayHello(ctx, reqbody.(*HelloRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func HelloworldService_CreateUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(HelloworldService).CreateUser(ctx, reqbody.(*CreateUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// requestBodyHelloworldServiceCreateUserRESTfulPath0 POST: /v1/greeter/user
type requestBodyHelloworldServiceCreateUserRESTfulPath0 struct{}

func (requestBodyHelloworldServiceCreateUserRESTfulPath0) Locate(message restful.ProtoMessage) interface{} {
	x := message.(*CreateUserRequest)
	return x
}

func (requestBodyHelloworldServiceCreateUserRESTfulPath0) Body() string {
	return "*"
}

// HelloworldServer_ServiceDesc descriptor for server.RegisterService.
var HelloworldServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "step3.helloworld.Helloworld",
	HandlerType: ((*HelloworldService)(nil)),
	Methods: []server.Method{
		{
			Name: "/step3.helloworld.Helloworld/SayHello",
			Func: HelloworldService_SayHello_Handler,
			Bindings: []*restful.Binding{{
				Name:  "/step3.helloworld.Helloworld/SayHello",
				Input: func() restful.ProtoMessage { return new(HelloRequest) },
				Filter: func(svc interface{}, ctx context.Context, reqbody interface{}) (interface{}, error) {
					return svc.(HelloworldService).SayHello(ctx, reqbody.(*HelloRequest))
				},
				HTTPMethod:   "GET",
				Pattern:      restful.Enforce("/v1/greeter/hello"),
				Body:         nil,
				ResponseBody: nil,
			}},
		},
		{
			Name: "/step3.helloworld.Helloworld/CreateUser",
			Func: HelloworldService_CreateUser_Handler,
			Bindings: []*restful.Binding{{
				Name:  "/step3.helloworld.Helloworld/CreateUser",
				Input: func() restful.ProtoMessage { return new(CreateUserRequest) },
				Filter: func(svc interface{}, ctx context.Context, reqbody interface{}) (interface{}, error) {
					return svc.(HelloworldService).CreateUser(ctx, reqbody.(*CreateUserRequest))
				},
				HTTPMethod:   "POST",
				Pattern:      restful.Enforce("/v1/greeter/user"),
				Body:         requestBodyHelloworldServiceCreateUserRESTfulPath0{},
				ResponseBody: nil,
			}},
		},
	},
}

// RegisterHelloworldService registers service.
func RegisterHelloworldService(s server.Service, svr HelloworldService) {
	if err := s.Register(&HelloworldServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Helloworld register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedHelloworld struct{}

// SayHello RESTful HTTP接口：通过用户ID获取问候信息
//
//	会内部调用UserService获取用户信息
//
// 映射 url: /v1/greeter/hello?user_id=1231
func (s *UnimplementedHelloworld) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, errors.New("rpc SayHello of service Helloworld is not implemented")
}

// CreateUser RESTful HTTP接口：创建用户（内部调用UserService的扩展接口）
func (s *UnimplementedHelloworld) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, errors.New("rpc CreateUser of service Helloworld is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// HelloworldClientProxy defines service client proxy
type HelloworldClientProxy interface {
	// SayHello RESTful HTTP接口：通过用户ID获取问候信息
	//  会内部调用UserService获取用户信息
	// 映射 url: /v1/greeter/hello?user_id=1231
	SayHello(ctx context.Context, req *HelloRequest, opts ...client.Option) (rsp *HelloResponse, err error)
	// CreateUser RESTful HTTP接口：创建用户（内部调用UserService的扩展接口）
	CreateUser(ctx context.Context, req *CreateUserRequest, opts ...client.Option) (rsp *CreateUserResponse, err error)
}

type HelloworldClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewHelloworldClientProxy = func(opts ...client.Option) HelloworldClientProxy {
	return &HelloworldClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *HelloworldClientProxyImpl) SayHello(ctx context.Context, req *HelloRequest, opts ...client.Option) (*HelloResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/step3.helloworld.Helloworld/SayHello")
	msg.WithCalleeServiceName(HelloworldServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Helloworld")
	msg.WithCalleeMethod("SayHello")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *HelloworldClientProxyImpl) CreateUser(ctx context.Context, req *CreateUserRequest, opts ...client.Option) (*CreateUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/step3.helloworld.Helloworld/CreateUser")
	msg.WithCalleeServiceName(HelloworldServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Helloworld")
	msg.WithCalleeMethod("CreateUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
