// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: go_zero_model_mysql.proto

package server

import (
	"context"

	"go_zero_model_mysql/go_zero_model_mysql"
	"go_zero_model_mysql/internal/logic"
	"go_zero_model_mysql/internal/svc"
)

type GoZeroModelMysqlServer struct {
	svcCtx *svc.ServiceContext
	go_zero_model_mysql.UnimplementedGoZeroModelMysqlServer
}

func NewGoZeroModelMysqlServer(svcCtx *svc.ServiceContext) *GoZeroModelMysqlServer {
	return &GoZeroModelMysqlServer{
		svcCtx: svcCtx,
	}
}

func (s *GoZeroModelMysqlServer) Ping(ctx context.Context, in *go_zero_model_mysql.Request) (*go_zero_model_mysql.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
