// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ArrayDef struct {
	Nums [10]int `json:"nums"`
}

type Bar struct {
	Foo int               `json:"foo"`
	Bar bool              `json:"bar"`
	Baz []string          `json:"baz"`
	Qux map[string]string `json:"qux"`
}

type CompanyItem struct {
	Name string      `json:"name"`
	Stud StudentItem `json:"stud"`
}

type ComposeData struct {
	Ns SliceDef `json:"ns"`
	Ss SliceDef `json:"ss"`
	Md MapDef   `json:"md"`
}

type DefEempty struct {
}

type DemoPath4Req struct {
	Id   int64  `path:"id"`
	Name string `path:"name"`
}

type DemoResp struct {
}

type FormExampleReq struct {
	Name string `form:"name"`
}

type IncludeBaseDef struct {
	Exist bool    `json:"exist"`
	Nums  uint8   `json:"nums"`
	N1    uint16  `json:"n1"`
	Nu32  uint32  `json:"nui32"`
	Nu64  uint64  `json:"nui64"`
	Ni8   int8    `json:"ni8"`
	Ni16  int16   `json:"ni16"`
	Ni32  int32   `json:"ni32"`
	Ni64  int64   `json:"ni64"`
	NF32  float32 `json:"nf32"`
	NF64  float64 `json:"nf64"`
	Ni    int     `json:"ni"`
	Nui   uint    `json:"nui"`
	NB    byte    `json:"nb"`
}

type ListItem struct {
	Value1 string `json:"value1"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Name string `json:"name"`
}

type MapDef struct {
	Age    int         `json:"age"`
	MapDat map[int]int `json:"mapData"`
}

type PathExampleReq struct {
	ID string `path:"id"`
}

type PathExampleResp struct {
	Name string `json:"name"`
}

type PersonReq struct {
	Name string `json:"name"`
}

type PersonRsp struct {
	Data string `json:"data"`
}

type SliceDef struct {
	Nums []int `json:"nums"`
}

type Student struct {
	Age  int    `json:"age"`
	Name string `json:"name"`
}

type StudentItem struct {
	Address string `json:"address"`
}

type UpdateReq struct {
	Arg1       string      `json:"arg1"`
	PersonData PersonReq   `json:"person"`
	CompanyV   CompanyItem `json:"company"`
	HeaderItem string      `header:"secretVal"`
}
