// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type FormExampleReq struct {
	Name string `form:"name"`
}

type ListItem struct {
	Value1 string `json:"value1"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Name string `json:"name"`
}

type PathExampleReq struct {
	ID string `path:"id"`
}

type PathExampleResp struct {
	Name string `json:"name"`
}

type PersonReq struct {
	Name string `json:"name"`
}

type PersonRsp struct {
	Data string `json:"data"`
}

type UpdateReq struct {
	Arg1       string    `json:"arg1"`
	PersonData PersonReq `json:"person"`
}
