// Package main is originally generated by trpc-cmdline v1.0.9.
// It is located at `project/cmd/client`.
// Run this file by executing `go run cmd/client/main.go` in the project directory.
package main

import (
	pb "helloworld/pb"

	_ "trpc.group/trpc-go/trpc-filter/debuglog"
	trpc "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/log"
)

func callGreeterHello() {
	proxy := pb.NewGreeterClientProxy(

		//指定连接某个ip和端口
		// client.WithTarget("ip://127.0.0.1:8001"),
		// client.WithProtocol("http"),

		//client.WithServiceName 来同时用 called 以及 name 作为 key 进行配置的寻找：比如使用 trpc.helloworld.Greeter
		// client.WithServiceName("trpc.helloworld.Greeter"),

		//  比如 使用 http.helloworld.Greeter 来路由
		client.WithServiceName("http.helloworld.Greeter"),
	)
	ctx := trpc.BackgroundContext()
	// Example usage of unary client.
	reply, err := proxy.Hello(ctx, &pb.HelloRequest{})
	if err != nil {
		log.Fatalf("err: %v", err)
	}
	log.Debugf("simple  rpc   receive: %+v", reply)
}

func main() {
	// Load configuration following the logic in trpc.NewServer.
	cfg, err := trpc.LoadConfig(trpc.ServerConfigPath)
	if err != nil {
		panic("load config fail: " + err.Error())
	}
	trpc.SetGlobalConfig(cfg)
	if err := trpc.Setup(cfg); err != nil {
		panic("setup plugin fail: " + err.Error())
	}
	callGreeterHello()
}
