// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type PRequest struct {
	Name        string `json:"name,optional"`
	FromGateway string `json:"from_gateway,optional"`
	TMs         int64  `json:"timestamp,optional"`
}

type PResponse struct {
	Address string `json:"address"`
}

type Request struct {
	ID string `path:"id,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
