// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 Tencent.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: pb/helloworld.proto

package helloworld

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HelloRequest is hello request.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_pb_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pb_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// HelloResponse is hello response.
type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_pb_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_pb_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_helloworld_proto protoreflect.FileDescriptor

const file_pb_helloworld_proto_rawDesc = "" +
	"\n" +
	"\x13pb/helloworld.proto\x12\x11trpc.student.demo\" \n" +
	"\fHelloRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"!\n" +
	"\rHelloResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2_\n" +
	"\x11HelloWorldService\x12J\n" +
	"\x05Hello\x12\x1f.trpc.student.demo.HelloRequest\x1a .trpc.student.demo.HelloResponseB\x14Z\x12student/helloworldb\x06proto3"

var (
	file_pb_helloworld_proto_rawDescOnce sync.Once
	file_pb_helloworld_proto_rawDescData []byte
)

func file_pb_helloworld_proto_rawDescGZIP() []byte {
	file_pb_helloworld_proto_rawDescOnce.Do(func() {
		file_pb_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_helloworld_proto_rawDesc), len(file_pb_helloworld_proto_rawDesc)))
	})
	return file_pb_helloworld_proto_rawDescData
}

var file_pb_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_helloworld_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: trpc.student.demo.HelloRequest
	(*HelloResponse)(nil), // 1: trpc.student.demo.HelloResponse
}
var file_pb_helloworld_proto_depIdxs = []int32{
	0, // 0: trpc.student.demo.HelloWorldService.Hello:input_type -> trpc.student.demo.HelloRequest
	1, // 1: trpc.student.demo.HelloWorldService.Hello:output_type -> trpc.student.demo.HelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_helloworld_proto_init() }
func file_pb_helloworld_proto_init() {
	if File_pb_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_helloworld_proto_rawDesc), len(file_pb_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_helloworld_proto_goTypes,
		DependencyIndexes: file_pb_helloworld_proto_depIdxs,
		MessageInfos:      file_pb_helloworld_proto_msgTypes,
	}.Build()
	File_pb_helloworld_proto = out.File
	file_pb_helloworld_proto_goTypes = nil
	file_pb_helloworld_proto_depIdxs = nil
}
