// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: greet.proto

package greet

import (
	"context"

	"rpc_demo_1/pb/gen/greet"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendMessage     = greet.SendMessage
	SendMessageReq  = greet.SendMessageReq
	SendMessageResp = greet.SendMessageResp

	Greet interface {
		// 定义客户端流式 rpc
		SendMessage(ctx context.Context, opts ...grpc.CallOption) (greet.Greet_SendMessageClient, error)
	}

	defaultGreet struct {
		cli zrpc.Client
	}
)

func NewGreet(cli zrpc.Client) Greet {
	return &defaultGreet{
		cli: cli,
	}
}

// 定义客户端流式 rpc
func (m *defaultGreet) SendMessage(ctx context.Context, opts ...grpc.CallOption) (greet.Greet_SendMessageClient, error) {
	client := greet.NewGreetClient(m.cli.Conn())
	return client.SendMessage(ctx, opts...)
}
