// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: rpc_demo_server1.proto

package server

import (
	"context"

	"rpc_demo_server1/internal/logic"
	"rpc_demo_server1/internal/svc"
	"rpc_demo_server1/rpc_demo_server1"
)

type RpcDemoServer1Server struct {
	svcCtx *svc.ServiceContext
	rpc_demo_server1.UnimplementedRpcDemoServer1Server
}

func NewRpcDemoServer1Server(svcCtx *svc.ServiceContext) *RpcDemoServer1Server {
	return &RpcDemoServer1Server{
		svcCtx: svcCtx,
	}
}

func (s *RpcDemoServer1Server) Ping(ctx context.Context, in *rpc_demo_server1.Request) (*rpc_demo_server1.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
