// Code generated by hertz generator.

package user

import (
	"context"
	user "hz-new-proto/biz/model/hz_new_idl_proto_demo/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Method1 .
// @router /hello [GET]
func Method1(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.HelloResp)
	//TODO:
	resp.RespBody = "this is hello request's response."

	c.JSON(consts.StatusOK, resp)
}

// Method2 .
// @router /other [POST]
func Method2(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.OtherReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.OtherResp)
	// TODO:
	resp.Resp = "this is other request's response."

	c.JSON(consts.StatusOK, resp)
}
