// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: go_zero_model_mysql.proto

package go_zero_model_mysql

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoZeroModelMysql_Ping_FullMethodName = "/go_zero_model_mysql.Go_zero_model_mysql/Ping"
)

// GoZeroModelMysqlClient is the client API for GoZeroModelMysql service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoZeroModelMysqlClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type goZeroModelMysqlClient struct {
	cc grpc.ClientConnInterface
}

func NewGoZeroModelMysqlClient(cc grpc.ClientConnInterface) GoZeroModelMysqlClient {
	return &goZeroModelMysqlClient{cc}
}

func (c *goZeroModelMysqlClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GoZeroModelMysql_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoZeroModelMysqlServer is the server API for GoZeroModelMysql service.
// All implementations must embed UnimplementedGoZeroModelMysqlServer
// for forward compatibility.
type GoZeroModelMysqlServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGoZeroModelMysqlServer()
}

// UnimplementedGoZeroModelMysqlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoZeroModelMysqlServer struct{}

func (UnimplementedGoZeroModelMysqlServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGoZeroModelMysqlServer) mustEmbedUnimplementedGoZeroModelMysqlServer() {}
func (UnimplementedGoZeroModelMysqlServer) testEmbeddedByValue()                          {}

// UnsafeGoZeroModelMysqlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoZeroModelMysqlServer will
// result in compilation errors.
type UnsafeGoZeroModelMysqlServer interface {
	mustEmbedUnimplementedGoZeroModelMysqlServer()
}

func RegisterGoZeroModelMysqlServer(s grpc.ServiceRegistrar, srv GoZeroModelMysqlServer) {
	// If the following call pancis, it indicates UnimplementedGoZeroModelMysqlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoZeroModelMysql_ServiceDesc, srv)
}

func _GoZeroModelMysql_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoZeroModelMysqlServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoZeroModelMysql_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoZeroModelMysqlServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GoZeroModelMysql_ServiceDesc is the grpc.ServiceDesc for GoZeroModelMysql service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoZeroModelMysql_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_zero_model_mysql.Go_zero_model_mysql",
	HandlerType: (*GoZeroModelMysqlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GoZeroModelMysql_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_zero_model_mysql.proto",
}
