// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "hz-new-proto/biz/model_gen/hz_new_idl_proto_demo/user"
)

// Method3 .
// @router /new [GET]
func Method3(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.OtherReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.OtherResp)

	c.JSON(consts.StatusOK, resp)
}
