// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: greet.proto

package server

import (
	"context"

	"rpc_demo_1/internal/logic/message"
	"rpc_demo_1/internal/svc"
	"rpc_demo_1/pb/gen"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	gen.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) Pong(ctx context.Context, in *gen.SendMessageReq) (*gen.SendMessageResp, error) {
	l := messagelogic.NewPongLogic(ctx, s.svcCtx)
	return l.Pong(in)
}
