// Code generated by MockGen. DO NOT EDIT.
// Source: stub/second_demo/helloworld/second_server.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=stub/second_demo/helloworld/second_server_mock.go -package=helloworld -self_package=second_demo/helloworld --source=stub/second_demo/helloworld/second_server.trpc.go
//

// Package helloworld is a generated GoMock package.
package helloworld

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockGreeterService is a mock of GreeterService interface.
type MockGreeterService struct {
	ctrl     *gomock.Controller
	recorder *MockGreeterServiceMockRecorder
}

// MockGreeterServiceMockRecorder is the mock recorder for MockGreeterService.
type MockGreeterServiceMockRecorder struct {
	mock *MockGreeterService
}

// NewMockGreeterService creates a new mock instance.
func NewMockGreeterService(ctrl *gomock.Controller) *MockGreeterService {
	mock := &MockGreeterService{ctrl: ctrl}
	mock.recorder = &MockGreeterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGreeterService) EXPECT() *MockGreeterServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockGreeterService) ISGOMOCK() struct{} {
	return struct{}{}
}

// SayHello mocks base method.
func (m *MockGreeterService) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SayHello", ctx, req)
	ret0, _ := ret[0].(*HelloReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHello indicates an expected call of SayHello.
func (mr *MockGreeterServiceMockRecorder) SayHello(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHello", reflect.TypeOf((*MockGreeterService)(nil).SayHello), ctx, req)
}

// MockHelloService is a mock of HelloService interface.
type MockHelloService struct {
	ctrl     *gomock.Controller
	recorder *MockHelloServiceMockRecorder
}

// MockHelloServiceMockRecorder is the mock recorder for MockHelloService.
type MockHelloServiceMockRecorder struct {
	mock *MockHelloService
}

// NewMockHelloService creates a new mock instance.
func NewMockHelloService(ctrl *gomock.Controller) *MockHelloService {
	mock := &MockHelloService{ctrl: ctrl}
	mock.recorder = &MockHelloServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloService) EXPECT() *MockHelloServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockHelloService) ISGOMOCK() struct{} {
	return struct{}{}
}

// SayHi mocks base method.
func (m *MockHelloService) SayHi(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SayHi", ctx, req)
	ret0, _ := ret[0].(*HelloReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHi indicates an expected call of SayHi.
func (mr *MockHelloServiceMockRecorder) SayHi(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHi", reflect.TypeOf((*MockHelloService)(nil).SayHi), ctx, req)
}

// MockGreeterClientProxy is a mock of GreeterClientProxy interface.
type MockGreeterClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockGreeterClientProxyMockRecorder
}

// MockGreeterClientProxyMockRecorder is the mock recorder for MockGreeterClientProxy.
type MockGreeterClientProxyMockRecorder struct {
	mock *MockGreeterClientProxy
}

// NewMockGreeterClientProxy creates a new mock instance.
func NewMockGreeterClientProxy(ctrl *gomock.Controller) *MockGreeterClientProxy {
	mock := &MockGreeterClientProxy{ctrl: ctrl}
	mock.recorder = &MockGreeterClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGreeterClientProxy) EXPECT() *MockGreeterClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockGreeterClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// SayHello mocks base method.
func (m *MockGreeterClientProxy) SayHello(ctx context.Context, req *HelloRequest, opts ...client.Option) (*HelloReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SayHello", varargs...)
	ret0, _ := ret[0].(*HelloReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHello indicates an expected call of SayHello.
func (mr *MockGreeterClientProxyMockRecorder) SayHello(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHello", reflect.TypeOf((*MockGreeterClientProxy)(nil).SayHello), varargs...)
}

// MockHelloClientProxy is a mock of HelloClientProxy interface.
type MockHelloClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockHelloClientProxyMockRecorder
}

// MockHelloClientProxyMockRecorder is the mock recorder for MockHelloClientProxy.
type MockHelloClientProxyMockRecorder struct {
	mock *MockHelloClientProxy
}

// NewMockHelloClientProxy creates a new mock instance.
func NewMockHelloClientProxy(ctrl *gomock.Controller) *MockHelloClientProxy {
	mock := &MockHelloClientProxy{ctrl: ctrl}
	mock.recorder = &MockHelloClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloClientProxy) EXPECT() *MockHelloClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockHelloClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// SayHi mocks base method.
func (m *MockHelloClientProxy) SayHi(ctx context.Context, req *HelloRequest, opts ...client.Option) (*HelloReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SayHi", varargs...)
	ret0, _ := ret[0].(*HelloReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHi indicates an expected call of SayHi.
func (mr *MockHelloClientProxyMockRecorder) SayHi(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHi", reflect.TypeOf((*MockHelloClientProxy)(nil).SayHi), varargs...)
}
