// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: pb/second_server.proto

// 格式为： trpc.{app}.{server}； 通常和下面的服务名 连接起来 等效于 配置文件的 name

package helloworld

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_pb_second_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_second_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pb_second_server_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_pb_second_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_second_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_pb_second_server_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_second_server_proto protoreflect.FileDescriptor

const file_pb_second_server_proto_rawDesc = "" +
	"\n" +
	"\x16pb/second_server.proto\x12\x16trpc.second.helloworld\" \n" +
	"\fHelloRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1e\n" +
	"\n" +
	"HelloReply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2a\n" +
	"\aGreeter\x12V\n" +
	"\bSayHello\x12$.trpc.second.helloworld.HelloRequest\x1a\".trpc.second.helloworld.HelloReply\"\x002\\\n" +
	"\x05Hello\x12S\n" +
	"\x05SayHi\x12$.trpc.second.helloworld.HelloRequest\x1a\".trpc.second.helloworld.HelloReply\"\x00B\x18Z\x16second_demo/helloworldb\x06proto3"

var (
	file_pb_second_server_proto_rawDescOnce sync.Once
	file_pb_second_server_proto_rawDescData []byte
)

func file_pb_second_server_proto_rawDescGZIP() []byte {
	file_pb_second_server_proto_rawDescOnce.Do(func() {
		file_pb_second_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_second_server_proto_rawDesc), len(file_pb_second_server_proto_rawDesc)))
	})
	return file_pb_second_server_proto_rawDescData
}

var file_pb_second_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_second_server_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: trpc.second.helloworld.HelloRequest
	(*HelloReply)(nil),   // 1: trpc.second.helloworld.HelloReply
}
var file_pb_second_server_proto_depIdxs = []int32{
	0, // 0: trpc.second.helloworld.Greeter.SayHello:input_type -> trpc.second.helloworld.HelloRequest
	0, // 1: trpc.second.helloworld.Hello.SayHi:input_type -> trpc.second.helloworld.HelloRequest
	1, // 2: trpc.second.helloworld.Greeter.SayHello:output_type -> trpc.second.helloworld.HelloReply
	1, // 3: trpc.second.helloworld.Hello.SayHi:output_type -> trpc.second.helloworld.HelloReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_second_server_proto_init() }
func file_pb_second_server_proto_init() {
	if File_pb_second_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_second_server_proto_rawDesc), len(file_pb_second_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_second_server_proto_goTypes,
		DependencyIndexes: file_pb_second_server_proto_depIdxs,
		MessageInfos:      file_pb_second_server_proto_msgTypes,
	}.Build()
	File_pb_second_server_proto = out.File
	file_pb_second_server_proto_goTypes = nil
	file_pb_second_server_proto_depIdxs = nil
}
