// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: pb/base/base.proto

// proto 包名

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_pb_base_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_pb_base_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_pb_base_base_proto_rawDescGZIP(), []int{0}
}

func (x *Base) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Base) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_base_base_proto protoreflect.FileDescriptor

const file_pb_base_base_proto_rawDesc = "" +
	"\n" +
	"\x12pb/base/base.proto\x12\x04base\",\n" +
	"\x04Base\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msgB\x14Z\x12rpc_demo_1/pb/baseb\x06proto3"

var (
	file_pb_base_base_proto_rawDescOnce sync.Once
	file_pb_base_base_proto_rawDescData []byte
)

func file_pb_base_base_proto_rawDescGZIP() []byte {
	file_pb_base_base_proto_rawDescOnce.Do(func() {
		file_pb_base_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_base_base_proto_rawDesc), len(file_pb_base_base_proto_rawDesc)))
	})
	return file_pb_base_base_proto_rawDescData
}

var file_pb_base_base_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_base_base_proto_goTypes = []any{
	(*Base)(nil), // 0: base.Base
}
var file_pb_base_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_base_base_proto_init() }
func file_pb_base_base_proto_init() {
	if File_pb_base_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_base_base_proto_rawDesc), len(file_pb_base_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_base_base_proto_goTypes,
		DependencyIndexes: file_pb_base_base_proto_depIdxs,
		MessageInfos:      file_pb_base_base_proto_msgTypes,
	}.Build()
	File_pb_base_base_proto = out.File
	file_pb_base_base_proto_goTypes = nil
	file_pb_base_base_proto_depIdxs = nil
}
