// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: rpc_demo_server2.proto

package server

import (
	"context"

	"rpc_demo_server2/internal/logic"
	"rpc_demo_server2/internal/svc"
	"rpc_demo_server2/rpc_demo_server2"
)

type RpcDemoServer2Server struct {
	svcCtx *svc.ServiceContext
	rpc_demo_server2.UnimplementedRpcDemoServer2Server
}

func NewRpcDemoServer2Server(svcCtx *svc.ServiceContext) *RpcDemoServer2Server {
	return &RpcDemoServer2Server{
		svcCtx: svcCtx,
	}
}

func (s *RpcDemoServer2Server) Ping(ctx context.Context, in *rpc_demo_server2.Request) (*rpc_demo_server2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
