// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: go_zero_model_mysql.proto

package gozeromodelmysqlclient

import (
	"context"

	"go_zero_model_mysql/go_zero_model_mysql"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = go_zero_model_mysql.Request
	Response = go_zero_model_mysql.Response

	GoZeroModelMysql interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultGoZeroModelMysql struct {
		cli zrpc.Client
	}
)

func NewGoZeroModelMysql(cli zrpc.Client) GoZeroModelMysql {
	return &defaultGoZeroModelMysql{
		cli: cli,
	}
}

func (m *defaultGoZeroModelMysql) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := go_zero_model_mysql.NewGoZeroModelMysqlClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
