// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"http_gateway_demo/upstreams-server/userservice/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/ping",
				Handler: UserservicePingHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/users",
				Handler: UserserviceUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/users/:id",
				Handler: UserserviceUserIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/users/post",
				Handler: UserServicePostHandler(serverCtx),
			},
		},
	)
}
