// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: rpc_demo_server1.proto

package rpcdemoserver1client

import (
	"context"

	"rpc_demo_server1/rpc_demo_server1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = rpc_demo_server1.Request
	Response = rpc_demo_server1.Response

	RpcDemoServer1 interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRpcDemoServer1 struct {
		cli zrpc.Client
	}
)

func NewRpcDemoServer1(cli zrpc.Client) RpcDemoServer1 {
	return &defaultRpcDemoServer1{
		cli: cli,
	}
}

func (m *defaultRpcDemoServer1) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpc_demo_server1.NewRpcDemoServer1Client(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
