// Code generated by MockGen. DO NOT EDIT.
// Source: stub/hello_world_demo/my_hello_world/helloworld.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=stub/hello_world_demo/my_hello_world/helloworld_mock.go -package=my_hello_world -self_package=hello_world_demo/my_hello_world --source=stub/hello_world_demo/my_hello_world/helloworld.trpc.go
//

// Package my_hello_world is a generated GoMock package.
package my_hello_world

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockStudentServiceService is a mock of StudentServiceService interface.
type MockStudentServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockStudentServiceServiceMockRecorder
}

// MockStudentServiceServiceMockRecorder is the mock recorder for MockStudentServiceService.
type MockStudentServiceServiceMockRecorder struct {
	mock *MockStudentServiceService
}

// NewMockStudentServiceService creates a new mock instance.
func NewMockStudentServiceService(ctrl *gomock.Controller) *MockStudentServiceService {
	mock := &MockStudentServiceService{ctrl: ctrl}
	mock.recorder = &MockStudentServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentServiceService) EXPECT() *MockStudentServiceServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockStudentServiceService) ISGOMOCK() struct{} {
	return struct{}{}
}

// Hello mocks base method.
func (m *MockStudentServiceService) Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello", ctx, req)
	ret0, _ := ret[0].(*HelloResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockStudentServiceServiceMockRecorder) Hello(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockStudentServiceService)(nil).Hello), ctx, req)
}

// MockStudentServiceClientProxy is a mock of StudentServiceClientProxy interface.
type MockStudentServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockStudentServiceClientProxyMockRecorder
}

// MockStudentServiceClientProxyMockRecorder is the mock recorder for MockStudentServiceClientProxy.
type MockStudentServiceClientProxyMockRecorder struct {
	mock *MockStudentServiceClientProxy
}

// NewMockStudentServiceClientProxy creates a new mock instance.
func NewMockStudentServiceClientProxy(ctrl *gomock.Controller) *MockStudentServiceClientProxy {
	mock := &MockStudentServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockStudentServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentServiceClientProxy) EXPECT() *MockStudentServiceClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockStudentServiceClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// Hello mocks base method.
func (m *MockStudentServiceClientProxy) Hello(ctx context.Context, req *HelloRequest, opts ...client.Option) (*HelloResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hello", varargs...)
	ret0, _ := ret[0].(*HelloResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockStudentServiceClientProxyMockRecorder) Hello(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockStudentServiceClientProxy)(nil).Hello), varargs...)
}
