// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: pb/helloworld.proto

package my_hello_world

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// StudentServiceService defines service.
type StudentServiceService interface {
	// Hello Hello says hello.
	Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) // @alias=/my_hello_world/hello
}

func StudentServiceService_Hello_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StudentServiceService).Hello(ctx, reqbody.(*HelloRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// StudentServiceServer_ServiceDesc descriptor for server.RegisterService.
var StudentServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.first.student.StudentService",
	HandlerType: ((*StudentServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.first.student.StudentService/Hello",
			Func: StudentServiceService_Hello_Handler,
		},
	},
}

// RegisterStudentServiceService registers service.
func RegisterStudentServiceService(s server.Service, svr StudentServiceService) {
	if err := s.Register(&StudentServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("StudentService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedStudentService struct{}

// Hello Hello says hello.
func (s *UnimplementedStudentService) Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, errors.New("rpc Hello of service StudentService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// StudentServiceClientProxy defines service client proxy
type StudentServiceClientProxy interface {
	// Hello Hello says hello.
	Hello(ctx context.Context, req *HelloRequest, opts ...client.Option) (rsp *HelloResponse, err error) // @alias=/my_hello_world/hello
}

type StudentServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewStudentServiceClientProxy = func(opts ...client.Option) StudentServiceClientProxy {
	return &StudentServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *StudentServiceClientProxyImpl) Hello(ctx context.Context, req *HelloRequest, opts ...client.Option) (*HelloResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.first.student.StudentService/Hello")
	msg.WithCalleeServiceName(StudentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("first")
	msg.WithCalleeServer("student")
	msg.WithCalleeService("StudentService")
	msg.WithCalleeMethod("Hello")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
