// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: rpc_demo_server2.proto

package rpcdemoserver2client

import (
	"context"

	"rpc_demo_server2/rpc_demo_server2"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = rpc_demo_server2.Request
	Response = rpc_demo_server2.Response

	RpcDemoServer2 interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRpcDemoServer2 struct {
		cli zrpc.Client
	}
)

func NewRpcDemoServer2(cli zrpc.Client) RpcDemoServer2 {
	return &defaultRpcDemoServer2{
		cli: cli,
	}
}

func (m *defaultRpcDemoServer2) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpc_demo_server2.NewRpcDemoServer2Client(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
