// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: rpc_server_etcd.proto

package server

import (
	"context"

	"rpc_server_etcd/internal/logic"
	"rpc_server_etcd/internal/svc"
	"rpc_server_etcd/rpc_server_etcd"
)

type RpcServerEtcdServer struct {
	svcCtx *svc.ServiceContext
	rpc_server_etcd.UnimplementedRpcServerEtcdServer
}

func NewRpcServerEtcdServer(svcCtx *svc.ServiceContext) *RpcServerEtcdServer {
	return &RpcServerEtcdServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServerEtcdServer) Ping(ctx context.Context, in *rpc_server_etcd.Request) (*rpc_server_etcd.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
