// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: greet.proto

package server

import (
	"rpc_demo_1/internal/logic/greet"
	"rpc_demo_1/internal/svc"
	"rpc_demo_1/pb/gen"
)

type GreetServer struct {
	svcCtx *svc.ServiceContext
	gen.UnimplementedGreetServer
}

func NewGreetServer(svcCtx *svc.ServiceContext) *GreetServer {
	return &GreetServer{
		svcCtx: svcCtx,
	}
}

// 定义客户端流式 rpc
func (s *GreetServer) SendMessage(stream gen.Greet_SendMessageServer) error {
	l := greetlogic.NewSendMessageLogic(stream.Context(), s.svcCtx)
	return l.SendMessage(stream)
}
