// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: demo.proto

package server

import (
	"context"

	"add_server_on_rpc/internal/logic/demo"
	"add_server_on_rpc/internal/svc"
	"add_server_on_rpc/pb/demo"
)

type DemoServer struct {
	svcCtx *svc.ServiceContext
	demo.UnimplementedDemoServer
}

func NewDemoServer(svcCtx *svc.ServiceContext) *DemoServer {
	return &DemoServer{
		svcCtx: svcCtx,
	}
}

func (s *DemoServer) Ping(ctx context.Context, in *demo.Request) (*demo.Response, error) {
	l := demologic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
