// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: greet.proto

package message

import (
	"context"

	"rpc_demo_1/pb/gen/greet"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendMessage     = greet.SendMessage
	SendMessageReq  = greet.SendMessageReq
	SendMessageResp = greet.SendMessageResp

	Message interface {
		Pong(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

func (m *defaultMessage) Pong(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := greet.NewMessageClient(m.cli.Conn())
	return client.Pong(ctx, in, opts...)
}
