// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"
	"time"

	g1 "add_server_on_service_http/internal/handler/g1"
	"add_server_on_service_http/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/foo/bar/:id/:name",
					Handler: g1.DemoPath4Handler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/form/example",
					Handler: g1.FormExampleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/form/getExample",
					Handler: g1.FormGetExampleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: g1.ListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/path/example/:id",
					Handler: g1.PathExampleHandler(serverCtx),
				},
				{
					// ping
					Method:  http.MethodGet,
					Path:    "/ping",
					Handler: g1.PingHandler(serverCtx),
				},
				{
					// 更新
					Method:  http.MethodPost,
					Path:    "/update",
					Handler: g1.UpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
		rest.WithTimeout(3000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: g1.LoginHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
		rest.WithTimeout(3000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
