// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: rpc_server_etcd.proto

package rpcserveretcdclient

import (
	"context"

	"rpc_server_etcd/rpc_server_etcd"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = rpc_server_etcd.Request
	Response = rpc_server_etcd.Response

	RpcServerEtcd interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRpcServerEtcd struct {
		cli zrpc.Client
	}
)

func NewRpcServerEtcd(cli zrpc.Client) RpcServerEtcd {
	return &defaultRpcServerEtcd{
		cli: cli,
	}
}

func (m *defaultRpcServerEtcd) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpc_server_etcd.NewRpcServerEtcdClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
