// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: rpc_demo_server1.proto

package rpc_demo_server1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcDemoServer1_Ping_FullMethodName = "/rpc_demo_server1.Rpc_demo_server1/Ping"
)

// RpcDemoServer1Client is the client API for RpcDemoServer1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcDemoServer1Client interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rpcDemoServer1Client struct {
	cc grpc.ClientConnInterface
}

func NewRpcDemoServer1Client(cc grpc.ClientConnInterface) RpcDemoServer1Client {
	return &rpcDemoServer1Client{cc}
}

func (c *rpcDemoServer1Client) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RpcDemoServer1_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcDemoServer1Server is the server API for RpcDemoServer1 service.
// All implementations must embed UnimplementedRpcDemoServer1Server
// for forward compatibility.
type RpcDemoServer1Server interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRpcDemoServer1Server()
}

// UnimplementedRpcDemoServer1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcDemoServer1Server struct{}

func (UnimplementedRpcDemoServer1Server) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcDemoServer1Server) mustEmbedUnimplementedRpcDemoServer1Server() {}
func (UnimplementedRpcDemoServer1Server) testEmbeddedByValue()                        {}

// UnsafeRpcDemoServer1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcDemoServer1Server will
// result in compilation errors.
type UnsafeRpcDemoServer1Server interface {
	mustEmbedUnimplementedRpcDemoServer1Server()
}

func RegisterRpcDemoServer1Server(s grpc.ServiceRegistrar, srv RpcDemoServer1Server) {
	// If the following call pancis, it indicates UnimplementedRpcDemoServer1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcDemoServer1_ServiceDesc, srv)
}

func _RpcDemoServer1_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDemoServer1Server).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDemoServer1_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDemoServer1Server).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcDemoServer1_ServiceDesc is the grpc.ServiceDesc for RpcDemoServer1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcDemoServer1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_demo_server1.Rpc_demo_server1",
	HandlerType: (*RpcDemoServer1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RpcDemoServer1_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_demo_server1.proto",
}
