// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: helloworld.proto

package pb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/restful"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// GreeterService defines service.
type GreeterService interface {
	SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error)

	DoPostMessage(ctx context.Context, req *PostMessageRequest) (*PostMessageResponse, error)
	// DoGetMessage GET 请求：/v1/get/info?age=1&address=shenzhen
	//  查询参数 age 和 address 自动映射到 GetMessageRequest 的同名字段
	DoGetMessage(ctx context.Context, req *GetMessageRequest) (*GetMessageResponse, error)
}

func GreeterService_SayHello_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(GreeterService).SayHello(ctx, reqbody.(*HelloRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func GreeterService_DoPostMessage_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &PostMessageRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(GreeterService).DoPostMessage(ctx, reqbody.(*PostMessageRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func GreeterService_DoGetMessage_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetMessageRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(GreeterService).DoGetMessage(ctx, reqbody.(*GetMessageRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// requestBodyGreeterServiceDoPostMessageRESTfulPath0 POST: /v2/update/info
type requestBodyGreeterServiceDoPostMessageRESTfulPath0 struct{}

func (requestBodyGreeterServiceDoPostMessageRESTfulPath0) Locate(message restful.ProtoMessage) interface{} {
	x := message.(*PostMessageRequest)
	return x
}

func (requestBodyGreeterServiceDoPostMessageRESTfulPath0) Body() string {
	return "*"
}

// GreeterServer_ServiceDesc descriptor for server.RegisterService.
var GreeterServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.examples.restful.helloworld.Greeter",
	HandlerType: ((*GreeterService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.examples.restful.helloworld.Greeter/SayHello",
			Func: GreeterService_SayHello_Handler,
			Bindings: []*restful.Binding{{
				Name:  "/trpc.examples.restful.helloworld.Greeter/SayHello",
				Input: func() restful.ProtoMessage { return new(HelloRequest) },
				Filter: func(svc interface{}, ctx context.Context, reqbody interface{}) (interface{}, error) {
					return svc.(GreeterService).SayHello(ctx, reqbody.(*HelloRequest))
				},
				HTTPMethod:   "GET",
				Pattern:      restful.Enforce("/v1/greeter/hello/{name}"),
				Body:         nil,
				ResponseBody: nil,
			}},
		},
		{
			Name: "/trpc.examples.restful.helloworld.Greeter/DoPostMessage",
			Func: GreeterService_DoPostMessage_Handler,
			Bindings: []*restful.Binding{{
				Name:  "/trpc.examples.restful.helloworld.Greeter/DoPostMessage",
				Input: func() restful.ProtoMessage { return new(PostMessageRequest) },
				Filter: func(svc interface{}, ctx context.Context, reqbody interface{}) (interface{}, error) {
					return svc.(GreeterService).DoPostMessage(ctx, reqbody.(*PostMessageRequest))
				},
				HTTPMethod:   "POST",
				Pattern:      restful.Enforce("/v2/update/info"),
				Body:         requestBodyGreeterServiceDoPostMessageRESTfulPath0{},
				ResponseBody: nil,
			}},
		},
		{
			Name: "/trpc.examples.restful.helloworld.Greeter/DoGetMessage",
			Func: GreeterService_DoGetMessage_Handler,
			Bindings: []*restful.Binding{{
				Name:  "/trpc.examples.restful.helloworld.Greeter/DoGetMessage",
				Input: func() restful.ProtoMessage { return new(GetMessageRequest) },
				Filter: func(svc interface{}, ctx context.Context, reqbody interface{}) (interface{}, error) {
					return svc.(GreeterService).DoGetMessage(ctx, reqbody.(*GetMessageRequest))
				},
				HTTPMethod:   "GET",
				Pattern:      restful.Enforce("/v1/get/info"),
				Body:         nil,
				ResponseBody: nil,
			}},
		},
	},
}

// RegisterGreeterService registers service.
func RegisterGreeterService(s server.Service, svr GreeterService) {
	if err := s.Register(&GreeterServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Greeter register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedGreeter struct{}

func (s *UnimplementedGreeter) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, errors.New("rpc SayHello of service Greeter is not implemented")
}
func (s *UnimplementedGreeter) DoPostMessage(ctx context.Context, req *PostMessageRequest) (*PostMessageResponse, error) {
	return nil, errors.New("rpc DoPostMessage of service Greeter is not implemented")
}

// DoGetMessage GET 请求：/v1/get/info?age=1&address=shenzhen
//
//	查询参数 age 和 address 自动映射到 GetMessageRequest 的同名字段
func (s *UnimplementedGreeter) DoGetMessage(ctx context.Context, req *GetMessageRequest) (*GetMessageResponse, error) {
	return nil, errors.New("rpc DoGetMessage of service Greeter is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// GreeterClientProxy defines service client proxy
type GreeterClientProxy interface {
	SayHello(ctx context.Context, req *HelloRequest, opts ...client.Option) (rsp *HelloReply, err error)

	DoPostMessage(ctx context.Context, req *PostMessageRequest, opts ...client.Option) (rsp *PostMessageResponse, err error)
	// DoGetMessage GET 请求：/v1/get/info?age=1&address=shenzhen
	//  查询参数 age 和 address 自动映射到 GetMessageRequest 的同名字段
	DoGetMessage(ctx context.Context, req *GetMessageRequest, opts ...client.Option) (rsp *GetMessageResponse, err error)
}

type GreeterClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewGreeterClientProxy = func(opts ...client.Option) GreeterClientProxy {
	return &GreeterClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *GreeterClientProxyImpl) SayHello(ctx context.Context, req *HelloRequest, opts ...client.Option) (*HelloReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.examples.restful.helloworld.Greeter/SayHello")
	msg.WithCalleeServiceName(GreeterServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Greeter")
	msg.WithCalleeMethod("SayHello")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *GreeterClientProxyImpl) DoPostMessage(ctx context.Context, req *PostMessageRequest, opts ...client.Option) (*PostMessageResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.examples.restful.helloworld.Greeter/DoPostMessage")
	msg.WithCalleeServiceName(GreeterServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Greeter")
	msg.WithCalleeMethod("DoPostMessage")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &PostMessageResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *GreeterClientProxyImpl) DoGetMessage(ctx context.Context, req *GetMessageRequest, opts ...client.Option) (*GetMessageResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.examples.restful.helloworld.Greeter/DoGetMessage")
	msg.WithCalleeServiceName(GreeterServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Greeter")
	msg.WithCalleeMethod("DoGetMessage")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetMessageResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
