// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type LoginReq struct {
	UserName string `json:"user_name,omitempty"`
	Passwd   string `json:"passwd"`
}

type LoginResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type SendReq struct {
	Age int `json:"age"`
}

type SendResponse struct {
	Name string `json:"name"`
}
