// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: rpc_demo_server2.proto

package rpc_demo_server2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcDemoServer2_Ping_FullMethodName = "/rpc_demo_server2.Rpc_demo_server2/Ping"
)

// RpcDemoServer2Client is the client API for RpcDemoServer2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcDemoServer2Client interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rpcDemoServer2Client struct {
	cc grpc.ClientConnInterface
}

func NewRpcDemoServer2Client(cc grpc.ClientConnInterface) RpcDemoServer2Client {
	return &rpcDemoServer2Client{cc}
}

func (c *rpcDemoServer2Client) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RpcDemoServer2_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcDemoServer2Server is the server API for RpcDemoServer2 service.
// All implementations must embed UnimplementedRpcDemoServer2Server
// for forward compatibility.
type RpcDemoServer2Server interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRpcDemoServer2Server()
}

// UnimplementedRpcDemoServer2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcDemoServer2Server struct{}

func (UnimplementedRpcDemoServer2Server) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcDemoServer2Server) mustEmbedUnimplementedRpcDemoServer2Server() {}
func (UnimplementedRpcDemoServer2Server) testEmbeddedByValue()                        {}

// UnsafeRpcDemoServer2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcDemoServer2Server will
// result in compilation errors.
type UnsafeRpcDemoServer2Server interface {
	mustEmbedUnimplementedRpcDemoServer2Server()
}

func RegisterRpcDemoServer2Server(s grpc.ServiceRegistrar, srv RpcDemoServer2Server) {
	// If the following call pancis, it indicates UnimplementedRpcDemoServer2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcDemoServer2_ServiceDesc, srv)
}

func _RpcDemoServer2_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcDemoServer2Server).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcDemoServer2_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcDemoServer2Server).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcDemoServer2_ServiceDesc is the grpc.ServiceDesc for RpcDemoServer2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcDemoServer2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_demo_server2.Rpc_demo_server2",
	HandlerType: (*RpcDemoServer2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RpcDemoServer2_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_demo_server2.proto",
}
