// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Id    int64  `json:"id"`
	Token string `json:"token"`
}
